/**
 * The only place this module reads the environment. Next inlines a
 * NEXT_PUBLIC_* variable only where written literally — see the equivalent
 * note in commercial-intelligence/env.ts, same reasoning here.
 */
export function readLossIntelligencePublicEnv(): Record<string, string | undefined> {
  return {
    NEXT_PUBLIC_LI_WINDOW_PRIMARY_WINDOW_MONTHS: process.env.NEXT_PUBLIC_LI_WINDOW_PRIMARY_WINDOW_MONTHS,
    NEXT_PUBLIC_LI_WINDOW_RECURRENCE_LOOKBACK_MONTHS: process.env.NEXT_PUBLIC_LI_WINDOW_RECURRENCE_LOOKBACK_MONTHS,
    NEXT_PUBLIC_LI_VALIDITY_MIN_REPEATED_SUPPLY_MONTHS: process.env.NEXT_PUBLIC_LI_VALIDITY_MIN_REPEATED_SUPPLY_MONTHS,
    NEXT_PUBLIC_LI_VALIDITY_LOW_SALE_RATIO: process.env.NEXT_PUBLIC_LI_VALIDITY_LOW_SALE_RATIO,
    NEXT_PUBLIC_LI_VALIDITY_LOCAL_OUTLIER_MAX_SHARE: process.env.NEXT_PUBLIC_LI_VALIDITY_LOCAL_OUTLIER_MAX_SHARE,
    NEXT_PUBLIC_LI_VALIDITY_NETWORK_WIDE_MIN_SHARE: process.env.NEXT_PUBLIC_LI_VALIDITY_NETWORK_WIDE_MIN_SHARE,
    NEXT_PUBLIC_LI_NETWORK_MIN_STORES_FOR_NETWORK_VERDICT: process.env.NEXT_PUBLIC_LI_NETWORK_MIN_STORES_FOR_NETWORK_VERDICT,
    NEXT_PUBLIC_LI_OTHER_REASON_MIN_HEALTHY_UNITS: process.env.NEXT_PUBLIC_LI_OTHER_REASON_MIN_HEALTHY_UNITS,
    NEXT_PUBLIC_LI_OTHER_REASON_VIABILITY_MAX_RATIO: process.env.NEXT_PUBLIC_LI_OTHER_REASON_VIABILITY_MAX_RATIO,
    NEXT_PUBLIC_LI_OTHER_REASON_NEGLIGIBLE_VALUE_CENTS: process.env.NEXT_PUBLIC_LI_OTHER_REASON_NEGLIGIBLE_VALUE_CENTS,
    NEXT_PUBLIC_LI_OTHER_REASON_LOCAL_CONCENTRATION_MIN: process.env.NEXT_PUBLIC_LI_OTHER_REASON_LOCAL_CONCENTRATION_MIN,
    NEXT_PUBLIC_LI_OTHER_REASON_MIN_RECURRING_PERIODS: process.env.NEXT_PUBLIC_LI_OTHER_REASON_MIN_RECURRING_PERIODS,
    NEXT_PUBLIC_LI_DAMAGE_LOCAL_CONCENTRATION_MIN: process.env.NEXT_PUBLIC_LI_DAMAGE_LOCAL_CONCENTRATION_MIN,
    NEXT_PUBLIC_LI_DAMAGE_MIN_STORES_CARRYING_FOR_CONCENTRATION: process.env.NEXT_PUBLIC_LI_DAMAGE_MIN_STORES_CARRYING_FOR_CONCENTRATION,
    NEXT_PUBLIC_LI_DAMAGE_MIN_STORES_FOR_SYSTEMIC: process.env.NEXT_PUBLIC_LI_DAMAGE_MIN_STORES_FOR_SYSTEMIC,
    NEXT_PUBLIC_LI_UNNECESSARY_SUPPLY_VERYLOW_SALE_RATIO: process.env.NEXT_PUBLIC_LI_UNNECESSARY_SUPPLY_VERYLOW_SALE_RATIO,
    NEXT_PUBLIC_LI_RECENT_HISTORY_MIN_CLOSED_MONTHS: process.env.NEXT_PUBLIC_LI_RECENT_HISTORY_MIN_CLOSED_MONTHS,
    NEXT_PUBLIC_LI_RECENT_HISTORY_MIN_UNITS: process.env.NEXT_PUBLIC_LI_RECENT_HISTORY_MIN_UNITS,
    NEXT_PUBLIC_LI_PRIORITY_CRITICAL_VALUE_CENTS: process.env.NEXT_PUBLIC_LI_PRIORITY_CRITICAL_VALUE_CENTS,
    NEXT_PUBLIC_LI_CONFIDENCE_MIN_MONTHS_FOR_HIGH: process.env.NEXT_PUBLIC_LI_CONFIDENCE_MIN_MONTHS_FOR_HIGH,
  };
}
