export type ParameterKind = "business" | "quality" | "analytic";
export type ParameterUnit = "share" | "ratio" | "count" | "months" | "cents" | "number";

export interface ParameterDoc {
  label: string;
  kind: ParameterKind;
  /** null quando o parâmetro não é uma razão calculada (ex.: uma contagem de meses). */
  formula: string | null;
  numerator: string;
  denominator: string;
  unit: ParameterUnit;
  window: string | null;
  why: string;
  controls: string;
  up: string;
  down: string;
  whenMissing: string;
  min: number;
  max: number;
  integer: boolean;
}

const d = (doc: ParameterDoc): ParameterDoc => doc;

export const PARAMETER_DOCS = {
  "window.primaryWindowMonths": d({
    label: "Janela principal (meses)",
    kind: "analytic",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "months",
    window: null,
    why: "3 meses fechados equilibra reação a padrões recentes com ruído de mês isolado — valor de julgamento, a calibrar.",
    controls: "Quantos períodos fechados entram no cálculo de todas as métricas primárias (§7).",
    up: "Menos ruído, reage mais devagar a mudanças recentes.",
    down: "Mais reativo, mais sujeito a ruído de um mês isolado.",
    whenMissing: "Usa quantos meses fechados existirem, se menos que o valor configurado.",
    min: 1,
    max: 12,
    integer: true,
  }),
  "window.recurrenceLookbackMonths": d({
    label: "Janela de recorrência (meses)",
    kind: "analytic",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "months",
    window: null,
    why: "6 meses dá margem para ver um padrão se repetir 2-3 vezes sem esperar o histórico inteiro.",
    controls: "Quantos períodos fechados entram no cálculo de recorrência (§10, §16), sem mudar a janela principal.",
    up: "Detecta padrões mais longos, mas mistura períodos mais antigos.",
    down: "Perde recorrência de médio prazo.",
    whenMissing: "Usa quantos meses fechados existirem, se menos que o valor configurado.",
    min: 2,
    max: 24,
    integer: true,
  }),
  "validity.minRepeatedSupplyMonths": d({
    label: "Validade: meses de abastecimento repetido",
    kind: "analytic",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "months",
    window: "janela principal",
    why: "2 meses evita marcar como padrão um único abastecimento isolado.",
    controls: "Caso A de validade (§10.1) — zero venda + validade só dispara com abastecimento repetido.",
    up: "Exige mais repetição antes de recomendar suspender.",
    down: "Suspende mais cedo, com menos repetição observada.",
    whenMissing: "—",
    min: 1,
    max: 6,
    integer: true,
  }),
  "validity.lowSaleRatio": d({
    label: "Validade: taxa vendido/abastecido baixa",
    kind: "analytic",
    formula: "vendido ÷ abastecido",
    numerator: "quantidade vendida na janela",
    denominator: "quantidade abastecida na janela",
    unit: "share",
    window: "janela principal",
    why: "Abaixo de 50% do abastecido vendido é o corte inicial de julgamento entre demanda saudável e possível excesso de envio.",
    controls: "Separa o caso B (reduzir) do caso C (manter+monitorar) em validade (§10.1).",
    up: "Mais produtos são classificados como excesso de abastecimento.",
    down: "Menos produtos são classificados como excesso.",
    whenMissing: "Indefinida se abastecido = 0 na janela.",
    min: 0,
    max: 1,
    integer: false,
  }),
  "validity.localOutlierMaxShare": d({
    label: "Validade: teto de lojas afetadas para outlier local",
    kind: "analytic",
    formula: "lojas com o mesmo sinal ruim ÷ lojas comparáveis",
    numerator: "lojas com o mesmo sinal de validade",
    denominator: "lojas onde o SKU é comparável (§12)",
    unit: "share",
    window: "janela principal",
    why: "Até 30% das lojas com o mesmo problema ainda é consistente com 'só esta loja tem o problema'.",
    controls: "Caso D de validade (§10.1) — escala suspender/reduzir para avaliar retirada da loja.",
    up: "Mais difícil escalar para retirada da loja (exige que a rede pareça mais saudável).",
    down: "Mais fácil escalar para retirada da loja.",
    whenMissing: "Usa dado_insuficiente de §12 — sem comparação de rede, nunca escala.",
    min: 0,
    max: 1,
    integer: false,
  }),
  "validity.networkWideMinShare": d({
    label: "Validade: piso de lojas afetadas para problema de rede",
    kind: "analytic",
    formula: "lojas com o mesmo sinal ruim ÷ lojas comparáveis",
    numerator: "lojas com o mesmo sinal de validade",
    denominator: "lojas onde o SKU é comparável (§12)",
    unit: "share",
    window: "janela principal",
    why: "70%+ das lojas com o mesmo problema já é evidência de que o problema é do produto, não da loja.",
    controls: "Caso E de validade (§10.1) — escala para avaliar retirada da rede.",
    up: "Mais difícil escalar para retirada da rede.",
    down: "Mais fácil escalar para retirada da rede.",
    whenMissing: "Usa dado_insuficiente de §12 — sem comparação de rede, nunca escala.",
    min: 0,
    max: 1,
    integer: false,
  }),
  "network.minStoresForNetworkVerdict": d({
    label: "Mínimo de lojas para veredito de rede",
    kind: "quality",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "count",
    window: "janela principal",
    why: "Menos de 5 lojas comparáveis não sustenta uma conclusão sobre 'a rede' — vira opinião sobre um punhado de casos.",
    controls: "Habilita ou desabilita a comparação de rede (§12) para qualquer motivo.",
    up: "Exige mais lojas antes de confiar numa comparação de rede.",
    down: "Compara com poucas lojas — menos confiável.",
    whenMissing: "Abaixo do mínimo, a comparação de rede fica dado_insuficiente.",
    min: 2,
    max: 50,
    integer: true,
  }),
  "otherReason.minHealthyUnits": d({
    label: "Outro motivo: unidades vendidas para 'saudável'",
    kind: "analytic",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "count",
    window: "janela principal",
    why: "20 unidades vendidas na janela é o piso de julgamento para considerar o produto comercialmente relevante nesta loja.",
    controls: "Condição de 'saudável' em §10.2 — sem isso, o produto nunca chega em manter/manter+monitorar por esta via.",
    up: "Mais exigente para considerar o produto saudável.",
    down: "Menos exigente.",
    whenMissing: "—",
    min: 0,
    max: 1000,
    integer: true,
  }),
  "otherReason.viabilityMaxRatio": d({
    label: "Outro motivo: perda tolerável sobre a margem",
    kind: "business",
    formula: "perda R$ ÷ margem bruta R$",
    numerator: "valor perdido em Outro motivo na janela",
    denominator: "margem bruta gerada pelo SKU nesta loja na janela",
    unit: "share",
    window: "janela principal",
    why: "Decisão de negócio: até que ponto a perda pode comer a margem gerada antes de a permanência do SKU precisar ser revista. 30% é o piso inicial de julgamento.",
    controls: "Corte do caso 'severo e recorrente' em §10.2 — acima disso, e recorrente, aciona avaliar permanência.",
    up: "Tolera mais perda antes de sugerir avaliar permanência.",
    down: "Sugere avaliar permanência com menos perda relativa.",
    whenMissing: "dados_insuficientes se margem bruta desconhecida — nunca assume margem.",
    min: 0,
    max: 1,
    integer: false,
  }),
  "otherReason.negligibleValueCents": d({
    label: "Outro motivo: perda desprezível",
    kind: "business",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "cents",
    window: "janela principal",
    why: "Decisão de negócio: abaixo de R$50 na janela, a perda não justifica sequer investigar.",
    controls: "Caso 'impacto desprezível' em §10.2 — mantém sem gerar ruído de investigação para valores pequenos.",
    up: "Mais casos viram 'manter' sem investigação.",
    down: "Mais casos entram na análise de recorrência/concentração.",
    whenMissing: "—",
    min: 0,
    max: 1000000,
    integer: true,
  }),
  "otherReason.localConcentrationMin": d({
    label: "Outro motivo: concentração numa loja",
    kind: "analytic",
    formula: "perda em Outro motivo nesta loja ÷ perda em Outro motivo do SKU em toda a rede",
    numerator: "valor perdido nesta loja",
    denominator: "valor perdido pelo SKU na rede inteira",
    unit: "share",
    window: "janela principal",
    why: "70% concentrado numa loja é o mesmo corte usado para dano (§10.3) — consistência entre as duas árvores que usam concentração.",
    controls: "Separa o caso 'recorrente ou concentrado' (investigar) do caso saudável isolado em §10.2.",
    up: "Mais exigente para afirmar concentração.",
    down: "Mais fácil afirmar concentração.",
    whenMissing: "Precisa do mesmo mínimo de lojas de network.minStoresForNetworkVerdict para ter significado.",
    min: 0,
    max: 1,
    integer: false,
  }),
  "otherReason.minRecurringPeriods": d({
    label: "Outro motivo: períodos para 'severo e recorrente'",
    kind: "analytic",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "months",
    window: "lookback de recorrência",
    why: "3 períodos com perda é o piso de julgamento para 'recorrente', consistente com o resto do motor.",
    controls: "Corte de recorrência do caso severo em §10.2 — sem isso, nunca aciona avaliar permanência.",
    up: "Exige mais repetição antes de avaliar permanência.",
    down: "Reage mais cedo.",
    whenMissing: "—",
    min: 1,
    max: 12,
    integer: true,
  }),
  "damage.localConcentrationMin": d({
    label: "Danificado: concentração numa loja",
    kind: "analytic",
    formula: "dano nesta loja ÷ dano do SKU em toda a rede",
    numerator: "unidades danificadas nesta loja",
    denominator: "unidades danificadas do SKU na rede inteira",
    unit: "share",
    window: "janela principal",
    why: "70% concentrado numa loja é evidência de causa provavelmente localizável (manuseio/armazenamento desta unidade).",
    controls: "Separa 'concentrado local' de 'espalhado na rede' em §10.3.",
    up: "Mais exigente para afirmar concentração local.",
    down: "Mais fácil afirmar concentração local.",
    whenMissing: "—",
    min: 0,
    max: 1,
    integer: false,
  }),
  "damage.minStoresCarryingForConcentration": d({
    label: "Danificado: mínimo de lojas para calcular concentração",
    kind: "quality",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "count",
    window: "janela principal",
    why: "Com menos de 3 lojas carregando o SKU, 'concentração' não tem significado estatístico.",
    controls: "Habilita o cálculo de concentração em §10.3 — abaixo disso, dados insuficientes.",
    up: "Exige mais lojas antes de calcular concentração.",
    down: "Calcula com menos lojas — menos confiável.",
    whenMissing: "Abaixo do mínimo, dados_insuficientes.",
    min: 1,
    max: 50,
    integer: true,
  }),
  "damage.minStoresForSystemic": d({
    label: "Danificado: mínimo de lojas para problema sistêmico",
    kind: "analytic",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "count",
    window: "janela principal",
    why: "4 lojas com dano recorrente e não-concentrado sustenta 'sistêmico' melhor que o mínimo de concentração — precisa ser igual ou maior.",
    controls: "Caso 'espalhado na rede' em §10.3.",
    up: "Mais exigente para afirmar problema sistêmico.",
    down: "Mais fácil afirmar.",
    whenMissing: "—",
    min: 1,
    max: 50,
    integer: true,
  }),
  "unnecessarySupply.verylowSaleRatio": d({
    label: "Abastecimento sem sentido: taxa vendido/abastecido baixíssima",
    kind: "analytic",
    formula: "vendido ÷ abastecido",
    numerator: "quantidade vendida na janela",
    denominator: "quantidade abastecida na janela",
    unit: "share",
    window: "janela principal",
    why: "15% é mais restrito que o corte de 'reduzir' de validade (50%) — este detector é para casos mais extremos, de prioridade alta.",
    controls: "Padrão 'zero/baixíssima venda + perda de validade' em §10.4.",
    up: "Menos casos disparam o detector.",
    down: "Mais casos disparam o detector.",
    whenMissing: "Indefinida se abastecido = 0.",
    min: 0,
    max: 1,
    integer: false,
  }),
  "recentHistory.minClosedMonths": d({
    label: "Histórico recente: meses mínimos",
    kind: "quality",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "months",
    window: null,
    why: "Menos de 2 meses fechados desde a primeira aparição não sustenta uma decisão estrutural sobre o SKU nesta loja.",
    controls: "Liga/desliga firstSeenRecently (§9) — modo protegido contra decisões prematuras.",
    up: "Protege por mais tempo.",
    down: "Protege por menos tempo.",
    whenMissing: "—",
    min: 0,
    max: 12,
    integer: true,
  }),
  "recentHistory.minUnits": d({
    label: "Histórico recente: unidades mínimas abastecidas",
    kind: "quality",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "count",
    window: null,
    why: "Menos de 15 unidades abastecidas desde a primeira aparição é amostra pequena demais para conclusão estrutural.",
    controls: "Liga/desliga firstSeenRecently (§9), junto com o critério de meses.",
    up: "Protege por mais tempo.",
    down: "Protege por menos tempo.",
    whenMissing: "—",
    min: 0,
    max: 1000,
    integer: true,
  }),
  "priority.criticalValueCents": d({
    label: "Prioridade: valor perdido para Crítica",
    kind: "business",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "cents",
    window: "janela principal",
    why: "Decisão de negócio: R$300 perdidos na janela, pelo motivo do diagnóstico prioritário, é o piso de julgamento para prioridade Crítica.",
    controls: "Corte Crítica vs Alta em §16.",
    up: "Menos casos viram Crítica.",
    down: "Mais casos viram Crítica.",
    whenMissing: "Não bloqueia — é valor de perda já valorado por finance-service, não depende de custo datado.",
    min: 0,
    max: 100000000,
    integer: true,
  }),
  "confidence.minMonthsForHigh": d({
    label: "Confiança: meses mínimos para Alta",
    kind: "quality",
    formula: null,
    numerator: "—",
    denominator: "—",
    unit: "months",
    window: "janela principal",
    why: "3 períodos qualificáveis sem contradição é o piso de julgamento para confiança Alta.",
    controls: "Corte Alta vs Média em §17.",
    up: "Mais exigente para confiança Alta.",
    down: "Menos exigente.",
    whenMissing: "—",
    min: 1,
    max: 12,
    integer: true,
  }),
} as const;

export type ParameterPath = keyof typeof PARAMETER_DOCS;

export const PARAMETER_PATHS = Object.keys(PARAMETER_DOCS) as ParameterPath[];

export const PARAMETER_KINDS: Record<ParameterKind, ParameterPath[]> = {
  business: PARAMETER_PATHS.filter((p) => PARAMETER_DOCS[p].kind === "business"),
  quality: PARAMETER_PATHS.filter((p) => PARAMETER_DOCS[p].kind === "quality"),
  analytic: PARAMETER_PATHS.filter((p) => PARAMETER_DOCS[p].kind === "analytic"),
};

export const KIND_LABELS: Record<ParameterKind, { title: string; description: string }> = {
  business: { title: "Regras de negócio", description: "Decisões da empresa — poucas, editáveis pelo gestor quando o registro oficial existir." },
  quality: { title: "Critérios de qualidade dos dados", description: "Decidem se há evidência suficiente para uma conclusão — nunca um ajuste de negócio." },
  analytic: { title: "Modelo analítico", description: "Como o motor de perdas classifica, prioriza e compara com a rede." },
};

export const PARAMETER_GROUP_LABELS: Record<string, string> = {
  window: "Janela de análise",
  validity: "Validade",
  network: "Comparação com a rede",
  otherReason: "Outro motivo",
  damage: "Danificado",
  unnecessarySupply: "Abastecimento sem sentido",
  recentHistory: "Histórico recente",
  priority: "Prioridade",
  confidence: "Confiança",
};
