/** Único lugar que lê `process.env` para este motor — Next só inlina NEXT_PUBLIC_* escrito literal. */
export function readRestockPublicEnv(): Record<string, string | undefined> {
  return {
    NEXT_PUBLIC_RESTOCK_EVIDENCE_MIN_MONTHS_WITH_SALES: process.env.NEXT_PUBLIC_RESTOCK_EVIDENCE_MIN_MONTHS_WITH_SALES,
    NEXT_PUBLIC_RESTOCK_TREND_RECENT_MONTHS_COUNT: process.env.NEXT_PUBLIC_RESTOCK_TREND_RECENT_MONTHS_COUNT,
    NEXT_PUBLIC_RESTOCK_TREND_RECENT_WEIGHT_MULTIPLIER: process.env.NEXT_PUBLIC_RESTOCK_TREND_RECENT_WEIGHT_MULTIPLIER,
    NEXT_PUBLIC_RESTOCK_TREND_UP_THRESHOLD_PCT: process.env.NEXT_PUBLIC_RESTOCK_TREND_UP_THRESHOLD_PCT,
    NEXT_PUBLIC_RESTOCK_TREND_DOWN_THRESHOLD_PCT: process.env.NEXT_PUBLIC_RESTOCK_TREND_DOWN_THRESHOLD_PCT,
    NEXT_PUBLIC_RESTOCK_TREND_ADJUST_PCT: process.env.NEXT_PUBLIC_RESTOCK_TREND_ADJUST_PCT,
    NEXT_PUBLIC_RESTOCK_TREND_VOLATILITY_THRESHOLD: process.env.NEXT_PUBLIC_RESTOCK_TREND_VOLATILITY_THRESHOLD,
    NEXT_PUBLIC_RESTOCK_ACTION_INCREASE_THRESHOLD_PCT: process.env.NEXT_PUBLIC_RESTOCK_ACTION_INCREASE_THRESHOLD_PCT,
    NEXT_PUBLIC_RESTOCK_ACTION_DECREASE_THRESHOLD_PCT: process.env.NEXT_PUBLIC_RESTOCK_ACTION_DECREASE_THRESHOLD_PCT,
    NEXT_PUBLIC_RESTOCK_LOSS_INTEGRATION_REDUCE_FACTOR: process.env.NEXT_PUBLIC_RESTOCK_LOSS_INTEGRATION_REDUCE_FACTOR,
    NEXT_PUBLIC_RESTOCK_CONFIDENCE_HIGH_MIN: process.env.NEXT_PUBLIC_RESTOCK_CONFIDENCE_HIGH_MIN,
    NEXT_PUBLIC_RESTOCK_CONFIDENCE_MEDIUM_MIN: process.env.NEXT_PUBLIC_RESTOCK_CONFIDENCE_MEDIUM_MIN,
  };
}
