/**
 * The only place the commercial-intelligence page reads the environment.
 *
 * Next inlines a `NEXT_PUBLIC_*` variable into the browser bundle only where it
 * is written literally as `process.env.NEXT_PUBLIC_X`; a lookup by name or a
 * copy of `process.env` is left as `undefined`. That is why every variable is
 * spelled out below instead of being looped over. The list is derived from
 * `PARAMETER_DOCS` and checked against it by the verification script, so a new
 * parameter cannot be added without its line here.
 *
 * A value change needs a rebuild (`admin-prod` takes it as a build argument).
 * Business rules read here are only the deployment default: their official,
 * single, audited value is the register of `add-commercial-intelligence-governance`.
 */
export function readPublicEnv(): Record<string, string | undefined> {
  return {
    NEXT_PUBLIC_CI_COUPON_EXCLUSION_COVERAGE: process.env.NEXT_PUBLIC_CI_COUPON_EXCLUSION_COVERAGE,
    NEXT_PUBLIC_CI_COUPON_FULL_COVERAGE: process.env.NEXT_PUBLIC_CI_COUPON_FULL_COVERAGE,
    NEXT_PUBLIC_CI_COUPON_MULTI_ITEM_SHARE_MIN: process.env.NEXT_PUBLIC_CI_COUPON_MULTI_ITEM_SHARE_MIN,
    NEXT_PUBLIC_CI_COUPON_ELIGIBLE_BASKETS_MIN_NETWORK: process.env.NEXT_PUBLIC_CI_COUPON_ELIGIBLE_BASKETS_MIN_NETWORK,
    NEXT_PUBLIC_CI_COUPON_ELIGIBLE_BASKETS_MIN_STORE: process.env.NEXT_PUBLIC_CI_COUPON_ELIGIBLE_BASKETS_MIN_STORE,
    NEXT_PUBLIC_CI_COUPON_SPAN_MAX_MINUTES: process.env.NEXT_PUBLIC_CI_COUPON_SPAN_MAX_MINUTES,
    NEXT_PUBLIC_CI_COUPON_MAX_SKUS_FOR_PAIRS: process.env.NEXT_PUBLIC_CI_COUPON_MAX_SKUS_FOR_PAIRS,
    NEXT_PUBLIC_CI_ASSOCIATION_MIN_SKU_BASKETS: process.env.NEXT_PUBLIC_CI_ASSOCIATION_MIN_SKU_BASKETS,
    NEXT_PUBLIC_CI_ASSOCIATION_MIN_PAIR_BASKETS: process.env.NEXT_PUBLIC_CI_ASSOCIATION_MIN_PAIR_BASKETS,
    NEXT_PUBLIC_CI_ASSOCIATION_Z: process.env.NEXT_PUBLIC_CI_ASSOCIATION_Z,
    NEXT_PUBLIC_CI_ASSOCIATION_LIFT_LOWER_BOUND_MIN: process.env.NEXT_PUBLIC_CI_ASSOCIATION_LIFT_LOWER_BOUND_MIN,
    NEXT_PUBLIC_CI_ASSOCIATION_STRONG_CONVERSION: process.env.NEXT_PUBLIC_CI_ASSOCIATION_STRONG_CONVERSION,
    NEXT_PUBLIC_CI_ASSOCIATION_FULL_PRICE_SHARE_NATURAL: process.env.NEXT_PUBLIC_CI_ASSOCIATION_FULL_PRICE_SHARE_NATURAL,
    NEXT_PUBLIC_CI_ASSOCIATION_KNOWN_PRICE_SHARE_MIN: process.env.NEXT_PUBLIC_CI_ASSOCIATION_KNOWN_PRICE_SHARE_MIN,
    NEXT_PUBLIC_CI_ASSOCIATION_ANCHOR_ONLY_BASKETS_MIN: process.env.NEXT_PUBLIC_CI_ASSOCIATION_ANCHOR_ONLY_BASKETS_MIN,
    NEXT_PUBLIC_CI_ASSOCIATION_PROMO_DISCOUNT_STEP: process.env.NEXT_PUBLIC_CI_ASSOCIATION_PROMO_DISCOUNT_STEP,
    NEXT_PUBLIC_CI_ASSOCIATION_PROMO_DISCOUNT_MAX: process.env.NEXT_PUBLIC_CI_ASSOCIATION_PROMO_DISCOUNT_MAX,
    NEXT_PUBLIC_CI_ASSOCIATION_PROMO_HEADROOM_CONVERSION_MAX: process.env.NEXT_PUBLIC_CI_ASSOCIATION_PROMO_HEADROOM_CONVERSION_MAX,
    NEXT_PUBLIC_CI_ASSOCIATION_EXPIRED_LOSS_SHARE_FOR_PROMO: process.env.NEXT_PUBLIC_CI_ASSOCIATION_EXPIRED_LOSS_SHARE_FOR_PROMO,
    NEXT_PUBLIC_CI_ASSOCIATION_TOP_NETWORK_PAIRS: process.env.NEXT_PUBLIC_CI_ASSOCIATION_TOP_NETWORK_PAIRS,
    NEXT_PUBLIC_CI_ASSOCIATION_DEVIATION_MIN_ANCHOR_BASKETS: process.env.NEXT_PUBLIC_CI_ASSOCIATION_DEVIATION_MIN_ANCHOR_BASKETS,
    NEXT_PUBLIC_CI_ASSOCIATION_DEVIATION_CONVERSION_RATIO: process.env.NEXT_PUBLIC_CI_ASSOCIATION_DEVIATION_CONVERSION_RATIO,
    NEXT_PUBLIC_CI_CART_GAP_MIN_ANCHOR_BASKETS_NETWORK: process.env.NEXT_PUBLIC_CI_CART_GAP_MIN_ANCHOR_BASKETS_NETWORK,
    NEXT_PUBLIC_CI_CART_GAP_MIN_ANCHOR_BASKETS_STORE: process.env.NEXT_PUBLIC_CI_CART_GAP_MIN_ANCHOR_BASKETS_STORE,
    NEXT_PUBLIC_CI_CART_GAP_REFERENCE_PERCENTILE: process.env.NEXT_PUBLIC_CI_CART_GAP_REFERENCE_PERCENTILE,
    NEXT_PUBLIC_CI_CART_GAP_REFERENCE_MIN_ANCHOR_BASKETS: process.env.NEXT_PUBLIC_CI_CART_GAP_REFERENCE_MIN_ANCHOR_BASKETS,
    NEXT_PUBLIC_CI_CART_GAP_PARTNER_BASE_RATE_MIN: process.env.NEXT_PUBLIC_CI_CART_GAP_PARTNER_BASE_RATE_MIN,
    NEXT_PUBLIC_CI_CART_GAP_PARTNER_BASE_RATE_MAX: process.env.NEXT_PUBLIC_CI_CART_GAP_PARTNER_BASE_RATE_MAX,
    NEXT_PUBLIC_CI_HOURLY_MIN_BASKETS_PER_DAYPART: process.env.NEXT_PUBLIC_CI_HOURLY_MIN_BASKETS_PER_DAYPART,
    NEXT_PUBLIC_CI_HOURLY_CONCENTRATION_RATIO: process.env.NEXT_PUBLIC_CI_HOURLY_CONCENTRATION_RATIO,
    NEXT_PUBLIC_CI_HOURLY_CONCENTRATION_MIN_BASKETS: process.env.NEXT_PUBLIC_CI_HOURLY_CONCENTRATION_MIN_BASKETS,
    NEXT_PUBLIC_CI_HOURLY_ATTACH_DIFF_MIN: process.env.NEXT_PUBLIC_CI_HOURLY_ATTACH_DIFF_MIN,
    NEXT_PUBLIC_CI_HOURLY_ATTACH_ZMIN: process.env.NEXT_PUBLIC_CI_HOURLY_ATTACH_ZMIN,
    NEXT_PUBLIC_CI_HOURLY_TICKET_UPLIFT: process.env.NEXT_PUBLIC_CI_HOURLY_TICKET_UPLIFT,
    NEXT_PUBLIC_CI_PRODUCTS_MIN_UNITS: process.env.NEXT_PUBLIC_CI_PRODUCTS_MIN_UNITS,
    NEXT_PUBLIC_CI_PRODUCTS_MIN_SELLING_DAYS: process.env.NEXT_PUBLIC_CI_PRODUCTS_MIN_SELLING_DAYS,
    NEXT_PUBLIC_CI_PRODUCTS_AVAILABILITY_SELLING_DAYS_SHARE_MIN: process.env.NEXT_PUBLIC_CI_PRODUCTS_AVAILABILITY_SELLING_DAYS_SHARE_MIN,
    NEXT_PUBLIC_CI_PRODUCTS_AVAILABILITY_GAP_DAYS: process.env.NEXT_PUBLIC_CI_PRODUCTS_AVAILABILITY_GAP_DAYS,
    NEXT_PUBLIC_CI_PRODUCTS_MOTOR_PERCENTILE: process.env.NEXT_PUBLIC_CI_PRODUCTS_MOTOR_PERCENTILE,
    NEXT_PUBLIC_CI_PRODUCTS_LOW_RETURN_CONTRIB_MAX: process.env.NEXT_PUBLIC_CI_PRODUCTS_LOW_RETURN_CONTRIB_MAX,
    NEXT_PUBLIC_CI_PRODUCTS_LOW_RETURN_QTY_MAX: process.env.NEXT_PUBLIC_CI_PRODUCTS_LOW_RETURN_QTY_MAX,
    NEXT_PUBLIC_CI_PRODUCTS_VOLUME_QTY_MIN: process.env.NEXT_PUBLIC_CI_PRODUCTS_VOLUME_QTY_MIN,
    NEXT_PUBLIC_CI_PRODUCTS_VOLUME_CONTRIB_MAX: process.env.NEXT_PUBLIC_CI_PRODUCTS_VOLUME_CONTRIB_MAX,
    NEXT_PUBLIC_CI_PRODUCTS_STAR_MIN: process.env.NEXT_PUBLIC_CI_PRODUCTS_STAR_MIN,
    NEXT_PUBLIC_CI_PRODUCTS_POTENTIAL_QTY_MAX: process.env.NEXT_PUBLIC_CI_PRODUCTS_POTENTIAL_QTY_MAX,
    NEXT_PUBLIC_CI_PRODUCTS_POTENTIAL_MARGIN_MIN: process.env.NEXT_PUBLIC_CI_PRODUCTS_POTENTIAL_MARGIN_MIN,
    NEXT_PUBLIC_CI_PEERS_COUNT: process.env.NEXT_PUBLIC_CI_PEERS_COUNT,
    NEXT_PUBLIC_CI_PEERS_MIN_BASKETS: process.env.NEXT_PUBLIC_CI_PEERS_MIN_BASKETS,
    NEXT_PUBLIC_CI_PEERS_SCALE_RATIO_MIN: process.env.NEXT_PUBLIC_CI_PEERS_SCALE_RATIO_MIN,
    NEXT_PUBLIC_CI_PEERS_SCALE_RATIO_MAX: process.env.NEXT_PUBLIC_CI_PEERS_SCALE_RATIO_MAX,
    NEXT_PUBLIC_CI_PEERS_MIN_FOR_BENCHMARK: process.env.NEXT_PUBLIC_CI_PEERS_MIN_FOR_BENCHMARK,
    NEXT_PUBLIC_CI_PEERS_TICKET_GAP_PCT: process.env.NEXT_PUBLIC_CI_PEERS_TICKET_GAP_PCT,
    NEXT_PUBLIC_CI_PEERS_GAP_T: process.env.NEXT_PUBLIC_CI_PEERS_GAP_T,
    NEXT_PUBLIC_CI_IMPACT_SCENARIO_CONSERVATIVE: process.env.NEXT_PUBLIC_CI_IMPACT_SCENARIO_CONSERVATIVE,
    NEXT_PUBLIC_CI_IMPACT_SCENARIO_EXPECTED: process.env.NEXT_PUBLIC_CI_IMPACT_SCENARIO_EXPECTED,
    NEXT_PUBLIC_CI_IMPACT_SCENARIO_OPTIMISTIC: process.env.NEXT_PUBLIC_CI_IMPACT_SCENARIO_OPTIMISTIC,
    NEXT_PUBLIC_CI_IMPACT_HIGH_SHARE_OF_MARGIN: process.env.NEXT_PUBLIC_CI_IMPACT_HIGH_SHARE_OF_MARGIN,
    NEXT_PUBLIC_CI_IMPACT_MEDIUM_SHARE_OF_MARGIN: process.env.NEXT_PUBLIC_CI_IMPACT_MEDIUM_SHARE_OF_MARGIN,
    NEXT_PUBLIC_CI_IMPACT_MIN_MONTHLY_CENTS: process.env.NEXT_PUBLIC_CI_IMPACT_MIN_MONTHLY_CENTS,
    NEXT_PUBLIC_CI_IMPACT_FLOOR_MONTHLY_CENTS: process.env.NEXT_PUBLIC_CI_IMPACT_FLOOR_MONTHLY_CENTS,
    NEXT_PUBLIC_CI_IMPACT_MAIN_SCREEN_ITEMS: process.env.NEXT_PUBLIC_CI_IMPACT_MAIN_SCREEN_ITEMS,
    NEXT_PUBLIC_CI_IMPACT_MAX_ITEMS: process.env.NEXT_PUBLIC_CI_IMPACT_MAX_ITEMS,
    NEXT_PUBLIC_CI_IMPACT_MAX_PER_DETECTOR: process.env.NEXT_PUBLIC_CI_IMPACT_MAX_PER_DETECTOR,
    NEXT_PUBLIC_CI_IMPACT_MAX_PER_STORE: process.env.NEXT_PUBLIC_CI_IMPACT_MAX_PER_STORE,
    NEXT_PUBLIC_CI_SIMULATOR_MIN_MARGIN_PCT: process.env.NEXT_PUBLIC_CI_SIMULATOR_MIN_MARGIN_PCT,
    NEXT_PUBLIC_CI_SIMULATOR_OBSERVED_PRICE_WINDOW_DAYS: process.env.NEXT_PUBLIC_CI_SIMULATOR_OBSERVED_PRICE_WINDOW_DAYS,
    NEXT_PUBLIC_CI_SIMULATOR_OBSERVED_PRICE_MIN_OBSERVATIONS: process.env.NEXT_PUBLIC_CI_SIMULATOR_OBSERVED_PRICE_MIN_OBSERVATIONS,
    NEXT_PUBLIC_CI_SIMULATOR_LIST_PRICE_DIVERGENCE: process.env.NEXT_PUBLIC_CI_SIMULATOR_LIST_PRICE_DIVERGENCE,
    NEXT_PUBLIC_CI_LOSS_DOMINANT_SHARE: process.env.NEXT_PUBLIC_CI_LOSS_DOMINANT_SHARE,
    NEXT_PUBLIC_CI_LOSS_SELL_THROUGH_LOW: process.env.NEXT_PUBLIC_CI_LOSS_SELL_THROUGH_LOW,
    NEXT_PUBLIC_CI_LOSS_SELL_THROUGH_HIGH: process.env.NEXT_PUBLIC_CI_LOSS_SELL_THROUGH_HIGH,
    NEXT_PUBLIC_CI_CONFIDENCE_HIGH_MIN: process.env.NEXT_PUBLIC_CI_CONFIDENCE_HIGH_MIN,
    NEXT_PUBLIC_CI_CONFIDENCE_MEDIUM_MIN: process.env.NEXT_PUBLIC_CI_CONFIDENCE_MEDIUM_MIN,
    NEXT_PUBLIC_CI_CONFIDENCE_DAYS_FULL: process.env.NEXT_PUBLIC_CI_CONFIDENCE_DAYS_FULL,
    NEXT_PUBLIC_CI_CONFIDENCE_DAYS_MID: process.env.NEXT_PUBLIC_CI_CONFIDENCE_DAYS_MID,
    NEXT_PUBLIC_CI_CONFIDENCE_DAYS_MIN: process.env.NEXT_PUBLIC_CI_CONFIDENCE_DAYS_MIN,
    NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_PAIR_MID: process.env.NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_PAIR_MID,
    NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_PAIR_HIGH: process.env.NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_PAIR_HIGH,
    NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_ANCHOR_MID: process.env.NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_ANCHOR_MID,
    NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_ANCHOR_HIGH: process.env.NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_ANCHOR_HIGH,
    NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_UNITS_MID: process.env.NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_UNITS_MID,
    NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_UNITS_HIGH: process.env.NEXT_PUBLIC_CI_CONFIDENCE_EVIDENCE_UNITS_HIGH,
    NEXT_PUBLIC_CI_CONFIDENCE_COUPON_COVERAGE_MID: process.env.NEXT_PUBLIC_CI_CONFIDENCE_COUPON_COVERAGE_MID,
    NEXT_PUBLIC_CI_CONFIDENCE_COST_HIGH: process.env.NEXT_PUBLIC_CI_CONFIDENCE_COST_HIGH,
    NEXT_PUBLIC_CI_CONFIDENCE_COST_MID: process.env.NEXT_PUBLIC_CI_CONFIDENCE_COST_MID,
    NEXT_PUBLIC_CI_CONFIDENCE_RECONCILIATION_FLAGGED_STORE_SHARE: process.env.NEXT_PUBLIC_CI_CONFIDENCE_RECONCILIATION_FLAGGED_STORE_SHARE,
    NEXT_PUBLIC_CI_CONFIDENCE_STORE_MIN_BASKETS: process.env.NEXT_PUBLIC_CI_CONFIDENCE_STORE_MIN_BASKETS,
    NEXT_PUBLIC_CI_CONFIDENCE_SCOPE_MIN_OK_LINES: process.env.NEXT_PUBLIC_CI_CONFIDENCE_SCOPE_MIN_OK_LINES,
    NEXT_PUBLIC_CI_QUALITY_UNRESOLVED_COST_REVENUE_SHARE_ATTENTION: process.env.NEXT_PUBLIC_CI_QUALITY_UNRESOLVED_COST_REVENUE_SHARE_ATTENTION,
    NEXT_PUBLIC_CI_QUALITY_HISTORY_MONTHS_FULL: process.env.NEXT_PUBLIC_CI_QUALITY_HISTORY_MONTHS_FULL,
    NEXT_PUBLIC_CI_QUALITY_DATED_LINES_FULL: process.env.NEXT_PUBLIC_CI_QUALITY_DATED_LINES_FULL,
    NEXT_PUBLIC_CI_QUALITY_DATED_LINES_MIN: process.env.NEXT_PUBLIC_CI_QUALITY_DATED_LINES_MIN,
    NEXT_PUBLIC_CI_QUALITY_ELIGIBLE_SKU_REVENUE_FULL: process.env.NEXT_PUBLIC_CI_QUALITY_ELIGIBLE_SKU_REVENUE_FULL,
    NEXT_PUBLIC_CI_QUALITY_ELIGIBLE_SKU_REVENUE_MIN: process.env.NEXT_PUBLIC_CI_QUALITY_ELIGIBLE_SKU_REVENUE_MIN,
    NEXT_PUBLIC_CI_QUALITY_CATALOG_SPARSE_CATEGORY_SHARE: process.env.NEXT_PUBLIC_CI_QUALITY_CATALOG_SPARSE_CATEGORY_SHARE,
  };
}

/**
 * True only for a run against a mock data source, where the entities named as
 * synthetic are kept (and labelled). On the real gateway it is unset, and a
 * store or product carrying the synthetic marker is excluded from every analysis.
 */
export const ALLOW_SYNTHETIC: boolean = process.env.NEXT_PUBLIC_ALLOW_SYNTHETIC === "true";
