/** Único lugar que lê `process.env` para este motor — Next só inlina NEXT_PUBLIC_* escrito literal. */
export function readMixPublicEnv(): Record<string, string | undefined> {
  return {
    NEXT_PUBLIC_MIX_EVIDENCE_MIN_MONTHS_WITH_SALES: process.env.NEXT_PUBLIC_MIX_EVIDENCE_MIN_MONTHS_WITH_SALES,
    NEXT_PUBLIC_MIX_TREND_RECENT_MONTHS_COUNT: process.env.NEXT_PUBLIC_MIX_TREND_RECENT_MONTHS_COUNT,
    NEXT_PUBLIC_MIX_TREND_RECENT_WEIGHT_MULTIPLIER: process.env.NEXT_PUBLIC_MIX_TREND_RECENT_WEIGHT_MULTIPLIER,
    NEXT_PUBLIC_MIX_TREND_UP_THRESHOLD_PCT: process.env.NEXT_PUBLIC_MIX_TREND_UP_THRESHOLD_PCT,
    NEXT_PUBLIC_MIX_TREND_DOWN_THRESHOLD_PCT: process.env.NEXT_PUBLIC_MIX_TREND_DOWN_THRESHOLD_PCT,
    NEXT_PUBLIC_MIX_TREND_ADJUST_PCT: process.env.NEXT_PUBLIC_MIX_TREND_ADJUST_PCT,
    NEXT_PUBLIC_MIX_TREND_VOLATILITY_THRESHOLD: process.env.NEXT_PUBLIC_MIX_TREND_VOLATILITY_THRESHOLD,
    NEXT_PUBLIC_MIX_CLASSIFICATION_AFFINITY_EXPLORE_MIN: process.env.NEXT_PUBLIC_MIX_CLASSIFICATION_AFFINITY_EXPLORE_MIN,
    NEXT_PUBLIC_MIX_CLASSIFICATION_AFFINITY_HEALTHY_MIN: process.env.NEXT_PUBLIC_MIX_CLASSIFICATION_AFFINITY_HEALTHY_MIN,
    NEXT_PUBLIC_MIX_CLASSIFICATION_MARGIN_HEALTHY_MIN_PCT: process.env.NEXT_PUBLIC_MIX_CLASSIFICATION_MARGIN_HEALTHY_MIN_PCT,
    NEXT_PUBLIC_MIX_OPPORTUNITY_MIN_NETWORK_STORES: process.env.NEXT_PUBLIC_MIX_OPPORTUNITY_MIN_NETWORK_STORES,
    NEXT_PUBLIC_MIX_OPPORTUNITY_TEST_QUANTITY: process.env.NEXT_PUBLIC_MIX_OPPORTUNITY_TEST_QUANTITY,
    NEXT_PUBLIC_MIX_CONFIDENCE_HIGH_MIN: process.env.NEXT_PUBLIC_MIX_CONFIDENCE_HIGH_MIN,
    NEXT_PUBLIC_MIX_CONFIDENCE_MEDIUM_MIN: process.env.NEXT_PUBLIC_MIX_CONFIDENCE_MEDIUM_MIN,
  };
}
